# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"naive_solution_to_max_sum_subarray_of_size_k": "00_slidingwindow.ipynb",
         "optimal_solution_to_max_sum_subarray_of_size_k": "00_slidingwindow.ipynb",
         "smallest_subarray_sum": "00_slidingwindow.ipynb",
         "longest_substring_with_k_distinct": "00_slidingwindow.ipynb",
         "fruits_into_basket": "00_slidingwindow.ipynb",
         "longest_substring_with_distinct_char": "00_slidingwindow.ipynb",
         "length_of_longest_substring": "00_slidingwindow.ipynb",
         "find_permutation": "00_slidingwindow.ipynb",
         "find_string_anagrams": "00_slidingwindow.ipynb",
         "find_substring": "00_slidingwindow.ipynb",
         "find_word_concatenation": "00_slidingwindow.ipynb"}

modules = ["slidingwindow.py"]

doc_url = "https://s13tc2.github.io/coding_patterns/"

git_url = "https://github.com/s13tc2/coding_patterns/tree/master/"

def custom_doc_links(name): return None
